export const COURSES = [
  {
    id: 1,
    title: "SQL Basics To Advanced Mastery Course",
    startDate: "20 Jul 2024",
    endDate: "28 Jul 2024",
    price: "0",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 2,
    title: "JavaScript Essentials",
    startDate: "01 Aug 2024",
    endDate: "15 Aug 2024",
    price: "50",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 3,
    title: "Python for Data Science",
    startDate: "01 Sep 2024",
    endDate: "30 Sep 2024",
    price: "100",
    validity: "90 days",
    isPublished: true,
  },
  {
    id: 4,
    title: "Web Development Bootcamp",
    startDate: "01 Oct 2024",
    endDate: "01 Nov 2024",
    price: "200",
    validity: "180 days",
    isPublished: false,
  },
  {
    id: 5,
    title: "Introduction to Machine Learning",
    startDate: "05 Nov 2024",
    endDate: "25 Nov 2024",
    price: "150",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 6,
    title: "Advanced React and Redux",
    startDate: "01 Dec 2024",
    endDate: "15 Dec 2024",
    price: "120",
    validity: "90 days",
    isPublished: false,
  },
  {
    id: 7,
    title: "Node.js Complete Guide",
    startDate: "20 Dec 2024",
    endDate: "10 Jan 2025",
    price: "130",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 8,
    title: "DevOps Essentials",
    startDate: "15 Aug 2024",
    endDate: "05 Sep 2024",
    price: "110",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 9,
    title: "Data Structures and Algorithms",
    startDate: "20 Sep 2024",
    endDate: "10 Oct 2024",
    price: "140",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 10,
    title: "Artificial Intelligence Fundamentals",
    startDate: "15 Oct 2024",
    endDate: "15 Nov 2024",
    price: "180",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 11,
    title: "Cybersecurity Basics",
    startDate: "20 Nov 2024",
    endDate: "05 Dec 2024",
    price: "90",
    validity: "90 days",
    isPublished: false,
  },
  {
    id: 12,
    title: "Introduction to Blockchain",
    startDate: "10 Dec 2024",
    endDate: "25 Dec 2024",
    price: "170",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 13,
    title: "Cloud Computing with AWS",
    startDate: "20 Dec 2024",
    endDate: "10 Jan 2025",
    price: "200",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 14,
    title: "Docker and Kubernetes Mastery",
    startDate: "15 Jan 2025",
    endDate: "05 Feb 2025",
    price: "160",
    validity: "180 days",
    isPublished: false,
  },
  {
    id: 15,
    title: "Java Programming for Beginners",
    startDate: "10 Feb 2025",
    endDate: "01 Mar 2025",
    price: "70",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 16,
    title: "Spring Framework in Depth",
    startDate: "05 Mar 2025",
    endDate: "25 Mar 2025",
    price: "140",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 17,
    title: "Android App Development",
    startDate: "30 Mar 2025",
    endDate: "20 Apr 2025",
    price: "130",
    validity: "365 days",
    isPublished: false,
  },
  {
    id: 18,
    title: "iOS App Development with Swift",
    startDate: "25 Apr 2025",
    endDate: "15 May 2025",
    price: "150",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 19,
    title: "Ruby on Rails Tutorial",
    startDate: "20 May 2025",
    endDate: "10 Jun 2025",
    price: "120",
    validity: "90 days",
    isPublished: true,
  },
  {
    id: 20,
    title: "Game Development with Unity",
    startDate: "15 Jun 2025",
    endDate: "05 Jul 2025",
    price: "160",
    validity: "180 days",
    isPublished: false,
  },
  {
    id: 21,
    title: "Introduction to Quantum Computing",
    startDate: "10 Jul 2025",
    endDate: "30 Jul 2025",
    price: "220",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 22,
    title: "Big Data Analysis with Hadoop",
    startDate: "01 Aug 2025",
    endDate: "20 Aug 2025",
    price: "210",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 23,
    title: "Deep Learning Specialization",
    startDate: "05 Sep 2025",
    endDate: "25 Sep 2025",
    price: "250",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 24,
    title: "Ethical Hacking",
    startDate: "01 Oct 2025",
    endDate: "20 Oct 2025",
    price: "190",
    validity: "90 days",
    isPublished: true,
  },
  {
    id: 25,
    title: "Full-Stack Web Development",
    startDate: "10 Oct 2025",
    endDate: "10 Nov 2025",
    price: "230",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 26,
    title: "Data Visualization with D3.js",
    startDate: "15 Nov 2025",
    endDate: "05 Dec 2025",
    price: "100",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 27,
    title: "Natural Language Processing",
    startDate: "01 Dec 2025",
    endDate: "20 Dec 2025",
    price: "200",
    validity: "365 days",
    isPublished: false,
  },
  {
    id: 28,
    title: "AR and VR Development",
    startDate: "05 Jan 2026",
    endDate: "25 Jan 2026",
    price: "240",
    validity: "180 days",
    isPublished: true,
  },
  {
    id: 29,
    title: "Introduction to Cyber-Physical Systems",
    startDate: "01 Feb 2026",
    endDate: "20 Feb 2026",
    price: "220",
    validity: "365 days",
    isPublished: true,
  },
  {
    id: 30,
    title: "Big Data in Healthcare",
    startDate: "10 Mar 2026",
    endDate: "30 Mar 2026",
    price: "210",
    validity: "180 days",
    isPublished: true,
  },
];

export const TABLE_HEADERS = [
  {
    id: 1,
    label: "Title",
    width: "30%",
  },
  {
    id: 2,
    label: "Start Date",
    width: "10%",
  },
  {
    id: 3,
    label: "End date",
    width: "10%",
  },
  {
    id: 4,
    label: "Price",
    width: "10%",
  },
  {
    id: 5,
    label: "Validity/Expiry",
    width: "15%",
  },
  {
    id: 6,
    label: "Status",
    width: "15%",
  },
];
